name: Build

on:
  workflow_run:
    workflows: ["Lint"]
    branches:
      - master
    types:
      - completed

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event != 'pull_request'
    name: Build, Push, & Deploy Container
    runs-on: ubuntu-latest

    steps:
      - name: Loud run!
        run: echo "Hello! I've run!"
