name: Build

on:
  on: workflow_dispatch

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success'
    name: Build, Push, & Deploy Container
    runs-on: ubuntu-latest

    steps:
      - name: Loud run!
        run: echo "Hello! I've run!"
