on:
  pull_request_review:


jobs:
  core-dev-check:
    name: At least one core developer needs to accept the PR
    runs-on: ubuntu-latest

    steps:
      - run: cat $GITHUB_EVENT_PATH

      - uses: octokit/graphql-action@v2.x
        id: reviews
        with:
          query: |
            query ($repository: String!, $pr: Int!) {
              repository(owner: "python-discord", name: $repository) {
                pullRequest(number: $pr) {
                  latestOpinionatedReviews(last: 100, writersOnly: true) {
                    nodes{
                      author{
                        login
                      }
                      state
                    }
                  }
                }
              }
            }
          repository: 'bot'
          pr: 1202
#          owner: ${{ github.event.repository.owner.login }}
#          repository: ${{ github.event.repository.name }}
#          pr: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_TOKEN }}

      - uses: octokit/graphql-action@v2.x
        id: core_developers
        with:
          query: |
            query {
              organization(login: "python-discord") {
                team(slug: "core-developers") {
                  members(first: 100) {
                    nodes {
                      login
                    }
                  }
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.TEAM_TOKEN }}

      - name: Setup python
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - run: |
          echo '${{ steps.reviews.outputs.data }}'
          echo '${{ steps.core_developers.outputs.data }}'

      - run: |
          python -c 'import json
          reviews = json.loads("""${{ steps.reviews.outputs.data }}""")
          reviewers = {
              review["author"]["login"]
              for review in reviews["repository"]["pullRequest"]["latestOpinionatedReviews"]["nodes"]
              if review["state"] == "APPROVED"
          }
          core_devs = json.loads("""${{ steps.core_developers.outputs.data }}""")
          core_devs = {
              member["login"] for member in core_devs["organization"]["team"]["members"]["nodes"]
          }
          print(reviewers)
          print(core_devs)
          approving_core_devs = reviewers & core_devs
          print(approving_core_devs)
          if not approving_core_devs:
              print("No approving Core Developers were found.")
              exit(1)
          '


