name: My test workflow

on:
  push:
    branches:
      - main

jobs:
  test-job:
    name: Test Action Environment
    runs-on: ubuntu-latest

    steps:
      - name: Test Action
        uses: SebastiaanZ/actions-playground@main
