name: My test workflow

on:
  push:
    branches:
      - main

jobs:
  embed-tester:
    name: Test GitHub Embed Action
    runs-on: ubuntu-latest

    steps:
      - name: Get Pull Request Information
        uses: octokit/request-action@v2.0.2
        id: pull_request
        with:
          route: GET /repos/{owner}/{repo}/pulls
          owner: python-discord
          repo: sir-lancebot
          state: open
          head: RohanJnr:error_handler_changes
          sort: updated
          direction: desc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Send an informational status embed to Discord instead of the
      # standard embeds that Discord sends. This embed will contain
      # more information and we can fine tune when we actually want
      # to send an embed.
      - name: GitHub Actions Status Embed for Discord
        uses: SebastiaanZ/github-status-embed-for-discord@v0.2.1
        with:
          # Our GitHub Actions webhook
          webhook_id: '784184528997842985'
          webhook_token: abcdefghijklmnop

          # Workflow information
          workflow_name: ${{ github.event.workflow_run.name }}
          run_id: ${{ github.event.workflow_run.id }}
          run_number: ${{ github.event.workflow_run.run_number }}
          status: ${{ github.event.workflow_run.conclusion }}
          actor: ${{ github.actor }}
          repository:  ${{ github.repository }}
          ref: ${{ github.ref }}
          sha: ${{ github.event.workflow_run.head_sha }}

          pull_request_payload: ${{ steps.pull_request.outputs.data }}
          dry_run: 1
          debug: 1
