name: My test workflow

on:
  push:
    branches:
      - main

jobs:
  embed-tester:
    name: Test GitHub Embed Action
    runs-on: ubuntu-latest

    steps:
      - name: Get Pull Request Information
        if: github.event.workflow_run.event == 'pull_request'
        uses: octokit/request-action@v2.0.2
        id: pull_request
        with:
          route: GET /repos/{owner}/{repo}/pulls
          owner: python-discord
          repo: sir-lancebot
          state: open
          head: RohanJnr:error_handler_changes
          sort: updated
          direction: desc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo '${{ toJson(steps.pull_request.outputs.data) }}'
