name: My test workflow

on:
  push:
    branches:
      - main

jobs:
  greeter:
    name: Greets someone
    runs-on: ubuntu-latest

    steps:
      - name: Greeter
        uses: SebastiaanZ/discord-status-embed@main

